In [115]:
import pandas as pd

In [116]:
df=pd.read_csv("amazon_prime_titles.csv")

In [117]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [118]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,NaN,113 min,"Comedy, Drama",A small fishing village must procure a local d...
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,110 min,"Drama, International",A Metro Family decides to fight a Cyber Crimin...
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,"March 30, 2021",2017,NaN,74 min,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...
3,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,"March 30, 2021",2014,NaN,69 min,Documentary,"Pink breaks the mold once again, bringing her ..."
4,s5,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,"March 30, 2021",1989,NaN,45 min,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...

In [119]:
df.nunique()

show_id         9668
type               2
title           9668
director        5773
cast            7927
country           86
date_added        84
release_year     100
rating            24
duration         219
listed_in        518
description     9414
dtype: int64

In [120]:
df.shape

(9668, 12)

In [121]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9668 entries, 0 to 9667
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       9668 non-null   object
 1   type          9668 non-null   object
 2   title         9668 non-null   object
 3   director      7585 non-null   object
 4   cast          8435 non-null   object
 5   country       672 non-null    object
 6   date_added    155 non-null    object
 7   release_year  9668 non-null   int64
 8   rating        9331 non-null   object
 9   duration      9668 non-null   object
 10  listed_in     9668 non-null   object
 11  description   9668 non-null   object
dtypes: int64(1), object(11)
memory usage: 906.5+ KB

In [122]:
df.describe()

       release_year
count   9668.000000
mean    2008.341849
std       18.922482
min     1920.000000
25%     2007.000000
50%     2016.000000
75%     2019.000000
max     2021.000000

In [123]:
df["director"].nunique()

5773

In [124]:
# Check how many rows have missing ratings
print(df['rating'].isnull().sum())

337

In [125]:
# Drop rows where rating is missing
df = df.dropna(subset=['rating'])

# Verify
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 9331 entries, 1 to 9667
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       9331 non-null   object
 1   type          9331 non-null   object
 2   title         9331 non-null   object
 3   director      7255 non-null   object
 4   cast          8123 non-null   object
 5   country       657 non-null    object
 6   date_added    140 non-null    object
 7   release_year  9331 non-null   int64
 8   rating        9331 non-null   object
 9   duration      9331 non-null   object
 10  listed_in     9331 non-null   object
 11  description   9331 non-null   object
dtypes: int64(1), object(11)
memory usage: 947.7+ KB
None

In [126]:
#Tried Creating Dictionary But Witnessed An Error
unique_values_dict = {
    col: df[col].unique().tolist()
    for col in df.columns
}

print(unique_values_dict)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

In [127]:
#Creating Unique Values Json File For Analysis
import json

with open("unique_values.json", "w", encoding="utf-8") as f:
    json.dump(unique_values_dict, f, indent=4, default=str)

In [128]:
#Replacing Few Ratings Which Aren't Useful 
rating_map = {
    '16': '16+',
    'AGES_16_': '16+',
    '18+': '18+',
    'AGES_18_': '18+',
    'ALL': 'ALL',
    'ALL_AGES': 'ALL',
    'NR': 'NOT_RATED',
    'UNRATED': 'NOT_RATED',
    'TV-NR': 'NOT_RATED',
    'NOT_RATE': 'NOT_RATED'
}

df['rating'] = df['rating'].replace(rating_map)

In [129]:
#Originally 25 rating reduced to 17
print(sorted(df['rating'].dropna().unique()))

['13+', '16+', '18+', '7+', 'ALL', 'G', 'NC-17', 'NOT_RATED', 'PG', 'PG-13', 'R', 'TV-14', 'TV-G', 'TV-MA', 'TV-PG', 'TV-Y', 'TV-Y7']

In [130]:
df["rating"].isna().sum()

np.int64(0)

In [131]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9331 entries, 1 to 9667
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       9331 non-null   object
 1   type          9331 non-null   object
 2   title         9331 non-null   object
 3   director      7255 non-null   object
 4   cast          8123 non-null   object
 5   country       657 non-null    object
 6   date_added    140 non-null    object
 7   release_year  9331 non-null   int64
 8   rating        9331 non-null   object
 9   duration      9331 non-null   object
 10  listed_in     9331 non-null   object
 11  description   9331 non-null   object
dtypes: int64(1), object(11)
memory usage: 947.7+ KB

In [132]:
#Now I Feel We Have Obtained A Dataset Where We Have Appropriate Ratings.

In [133]:
'''
Checking The Genre Of Each Movie/Show ➡️ Observation : Observed A Lot Many Genres Then Actually Present As It Contains A 
                                                        Mixture Of Different Genres.Now Let's Brainstorm What We Can Do 🤔.
'''
print(sorted(df['listed_in'].unique()))

['Action', 'Action, Adventure', 'Action, Adventure, Animation', 'Action, Adventure, Anime', 'Action, Adventure, Comedy', 'Action, Adventure, Documentary', 'Action, Adventure, Drama', 'Action, Adventure, Faith and Spirituality', 'Action, Adventure, Fantasy', 'Action, Adventure, Horror', 'Action, Adventure, International', 'Action, Adventure, Kids', 'Action, Adventure, Science Fiction', 'Action, Adventure, Special Interest', 'Action, Adventure, Sports', 'Action, Adventure, Suspense', 'Action, Adventure, Western', 'Action, Animation', 'Action, Animation, Anime', 'Action, Animation, Drama', 'Action, Animation, Fantasy', 'Action, Animation, Kids', 'Action, Animation, Science Fiction', 'Action, Anime', 'Action, Anime, Comedy', 'Action, Anime, Drama', 'Action, Anime, Fantasy', 'Action, Anime, International', 'Action, Anime, Kids', 'Action, Arthouse, Arts, Entertainment, and Culture', 'Action, Arthouse, Drama', 'Action, Arthouse, Horror', 'Action, Arts, Entertainment, and Culture', 'Action, Arts, Entertainment, and Culture, Comedy', 'Action, Arts, Entertainment, and Culture, Drama', 'Action, Arts, Entertainment, and Culture, Music Videos and Concerts', 'Action, Arts, Entertainment, and Culture, Suspense', 'Action, Comedy', 'Action, Comedy, Documentary', 'Action, Comedy, Drama', 'Action, Comedy, Fantasy', 'Action, Comedy, Horror', 'Action, Comedy, International', 'Action, Comedy, Kids', 'Action, Comedy, LGBTQ', 'Action, Comedy, Military and War', 'Action, Comedy, Romance', 'Action, Comedy, Science Fiction', 'Action, Comedy, Special Interest', 'Action, Comedy, Suspense', 'Action, Comedy, Western', 'Action, Comedy, Young Adult Audience', 'Action, Documentary', 'Action, Documentary, Drama', 'Action, Documentary, Faith and Spirituality', 'Action, Documentary, Special Interest', 'Action, Documentary, Sports', 'Action, Documentary, Unscripted', 'Action, Drama', 'Action, Drama, Faith and Spirituality', 'Action, Drama, Fantasy', 'Action, Drama, Historical', 'Action, Drama, Horror', 'Action, Drama, International', 'Action, Drama, Kids', 'Action, Drama, Military and War', 'Action, Drama, Romance', 'Action, Drama, Science Fiction', 'Action, Drama, Special Interest', 'Action, Drama, Sports', 'Action, Drama, Suspense', 'Action, Drama, Western', 'Action, Fantasy', 'Action, Fantasy, Science Fiction', 'Action, Fantasy, Suspense', 'Action, Horror', 'Action, Horror, Science Fiction', 'Action, Horror, Suspense', 'Action, International', 'Action, International, Romance', 'Action, International, Science Fiction', 'Action, International, Suspense', 'Action, Kids', 'Action, Kids, Military and War', 'Action, Kids, Science Fiction', 'Action, Kids, Suspense', 'Action, Kids, Young Adult Audience', 'Action, Military and War', 'Action, Military and War, Suspense', 'Action, Military and War, Western', 'Action, Romance', 'Action, Romance, Science Fiction', 'Action, Romance, Suspense', 'Action, Romance, Western', 'Action, Science Fiction', 'Action, Science Fiction, Suspense', 'Action, Special Interest', 'Action, Special Interest, Sports', 'Action, Special Interest, Suspense', 'Action, Sports', 'Action, Sports, Suspense', 'Action, Suspense', 'Action, Suspense, Unscripted', 'Action, Suspense, Young Adult Audience', 'Action, Unscripted', 'Action, Western', 'Action, Young Adult Audience', 'Adventure', 'Adventure, Animation, Kids', 'Adventure, Arthouse, Horror', 'Adventure, Comedy', 'Adventure, Comedy, Drama', 'Adventure, Comedy, Fantasy', 'Adventure, Comedy, Kids', 'Adventure, Comedy, Unscripted', 'Adventure, Documentary, Military and War', 'Adventure, Documentary, Special Interest', 'Adventure, Drama', 'Adventure, Drama, Faith and Spirituality', 'Adventure, Drama, Fantasy', 'Adventure, Drama, Kids', 'Adventure, Drama, Military and War', 'Adventure, Drama, Romance', 'Adventure, Drama, Suspense', 'Adventure, Drama, Western', 'Adventure, Fantasy', 'Adventure, International, Suspense', 'Adventure, Kids', 'Adventure, Kids, Science Fiction', 'Adventure, Science Fiction, Suspense', 'Adventure, Sports', 'Adventure, Suspense', 'Adventure, Western', 'Animation', 'Animation, Anime', 'Animation, Anime, Drama', 'Animation, Anime, Fantasy', 'Animation, Anime, Horror', 'Animation, Anime, Kids', 'Animation, Anime, Romance', 'Animation, Arts, Entertainment, and Culture, Comedy', 'Animation, Comedy', 'Animation, Comedy, Drama', 'Animation, Comedy, Kids', 'Animation, Comedy, Science Fiction', 'Animation, Documentary, Kids', 'Animation, Drama', 'Animation, Drama, Faith and Spirituality', 'Animation, Drama, Kids', 'Animation, Drama, Science Fiction', 'Animation, Faith and Spirituality, Kids', 'Animation, Horror', 'Animation, International, Kids', 'Animation, Kids', 'Animation, Kids, Music Videos and Concerts', 'Animation, Kids, Science Fiction', 'Animation, Kids, Special Interest', 'Animation, Kids, Sports', 'Animation, Kids, Suspense', 'Animation, Kids, Young Adult Audience', 'Animation, Music Videos and Concerts', 'Animation, Romance', 'Animation, Science Fiction', 'Animation, Special Interest', 'Animation, Suspense', 'Animation, Young Adult Audience', 'Anime', 'Anime, Comedy, Drama', 'Anime, Comedy, International', 'Anime, Drama', 'Anime, Drama, International', 'Anime, Drama, Sports', 'Anime, International, Kids', 'Anime, Kids', 'Anime, Kids, Science Fiction', 'Arthouse', 'Arthouse, Arts, Entertainment, and Culture', 'Arthouse, Arts, Entertainment, and Culture, Comedy', 'Arthouse, Arts, Entertainment, and Culture, Documentary', 'Arthouse, Arts, Entertainment, and Culture, Drama', 'Arthouse, Arts, Entertainment, and Culture, Horror', 'Arthouse, Comedy', 'Arthouse, Comedy, Documentary', 'Arthouse, Comedy, Drama', 'Arthouse, Comedy, Horror', 'Arthouse, Comedy, International', 'Arthouse, Comedy, LGBTQ', 'Arthouse, Comedy, Romance', 'Arthouse, Comedy, Science Fiction', 'Arthouse, Comedy, Special Interest', 'Arthouse, Documentary', 'Arthouse, Documentary, Music Videos and Concerts', 'Arthouse, Documentary, Special Interest', 'Arthouse, Drama', 'Arthouse, Drama, Horror', 'Arthouse, Drama, International', 'Arthouse, Drama, Kids', 'Arthouse, Drama, LGBTQ', 'Arthouse, Drama, Romance', 'Arthouse, Drama, Science Fiction', 'Arthouse, Drama, Suspense', 'Arthouse, Horror', 'Arthouse, Horror, International', 'Arthouse, Horror, Romance', 'Arthouse, Horror, Science Fiction', 'Arthouse, Horror, Suspense', 'Arthouse, LGBTQ, Romance', 'Arthouse, LGBTQ, Suspense', 'Arthouse, Romance', 'Arthouse, Special Interest', 'Arthouse, Young Adult Audience', 'Arts, Entertainment, and Culture', 'Arts, Entertainment, and Culture, Comedy', 'Arts, Entertainment, and Culture, Comedy, Documentary', 'Arts, Entertainment, and Culture, Comedy, Drama', 'Arts, Entertainment, and Culture, Comedy, Faith and Spirituality', 'Arts, Entertainment, and Culture, Comedy, Horror', 'Arts, Entertainment, and Culture, Comedy, International', 'Arts, Entertainment, and Culture, Comedy, Kids', 'Arts, Entertainment, and Culture, Comedy, LGBTQ', 'Arts, Entertainment, and Culture, Comedy, Military and War', 'Arts, Entertainment, and Culture, Comedy, Romance', 'Arts, Entertainment, and Culture, Comedy, Science Fiction', 'Arts, Entertainment, and Culture, Comedy, Special Interest', 'Arts, Entertainment, and Culture, Comedy, Suspense', 'Arts, Entertainment, and Culture, Comedy, Talk Show and Variety', 'Arts, Entertainment, and Culture, Comedy, Unscripted', 'Arts, Entertainment, and Culture, Comedy, Young Adult Audience', 'Arts, Entertainment, and Culture, Documentary', 'Arts, Entertainment, and Culture, Documentary, International', 'Arts, Entertainment, and Culture, Documentary, LGBTQ', 'Arts, Entertainment, and Culture, Documentary, Music Videos and Concerts', 'Arts, Entertainment, and Culture, Documentary, Special Interest', 'Arts, Entertainment, and Culture, Drama', 'Arts, Entertainment, and Culture, Drama, Horror', 'Arts, Entertainment, and Culture, Drama, International', 'Arts, Entertainment, and Culture, Drama, Kids', 'Arts, Entertainment, and Culture, Drama, LGBTQ', 'Arts, Entertainment, and Culture, Drama, Music Videos and Concerts', 'Arts, Entertainment, and Culture, Drama, Romance', 'Arts, Entertainment, and Culture, Drama, Science Fiction', 'Arts, Entertainment, and Culture, Drama, Suspense', 'Arts, Entertainment, and Culture, Drama, Western', 'Arts, Entertainment, and Culture, Drama, Young Adult Audience', 'Arts, Entertainment, and Culture, Fantasy, Horror', 'Arts, Entertainment, and Culture, Fantasy, Kids', 'Arts, Entertainment, and Culture, Fantasy, Science Fiction', 'Arts, Entertainment, and Culture, Horror, Suspense', 'Arts, Entertainment, and Culture, International', 'Arts, Entertainment, and Culture, International, Unscripted', 'Arts, Entertainment, and Culture, Kids', 'Arts, Entertainment, and Culture, Kids, Science Fiction', 'Arts, Entertainment, and Culture, LGBTQ', 'Arts, Entertainment, and Culture, LGBTQ, Romance', 'Arts, Entertainment, and Culture, Music Videos and Concerts', 'Arts, Entertainment, and Culture, Music Videos and Concerts, Special Interest', 'Arts, Entertainment, and Culture, Romance', 'Arts, Entertainment, and Culture, Special Interest, Unscripted', 'Arts, Entertainment, and Culture, Young Adult Audience', 'Comedy', 'Comedy, Documentary', 'Comedy, Documentary, Drama', 'Comedy, Documentary, Special Interest', 'Comedy, Documentary, Sports', 'Comedy, Documentary, Unscripted', 'Comedy, Drama', 'Comedy, Drama, Faith and Spirituality', 'Comedy, Drama, Fantasy', 'Comedy, Drama, Horror', 'Comedy, Drama, International', 'Comedy, Drama, Kids', 'Comedy, Drama, LGBTQ', 'Comedy, Drama, Military and War', 'Comedy, Drama, Music Videos and Concerts', 'Comedy, Drama, Romance', 'Comedy, Drama, Science Fiction', 'Comedy, Drama, Special Interest', 'Comedy, Drama, Sports', 'Comedy, Drama, Suspense', 'Comedy, Drama, Western', 'Comedy, Drama, Young Adult Audience', 'Comedy, Faith and Spirituality, Kids', 'Comedy, Fantasy', 'Comedy, Fantasy, Kids', 'Comedy, Fantasy, Young Adult Audience', 'Comedy, Historical', 'Comedy, Horror', 'Comedy, Horror, Kids', 'Comedy, Horror, Romance', 'Comedy, Horror, Science Fiction', 'Comedy, Horror, Suspense', 'Comedy, Horror, Young Adult Audience', 'Comedy, International', 'Comedy, International, LGBTQ', 'Comedy, International, Romance', 'Comedy, International, Special Interest', 'Comedy, International, Unscripted', 'Comedy, International, Young Adult Audience', 'Comedy, Kids', 'Comedy, Kids, LGBTQ', 'Comedy, Kids, Science Fiction', 'Comedy, Kids, Talk Show and Variety', 'Comedy, LGBTQ', 'Comedy, LGBTQ, Romance', 'Comedy, Military and War, Suspense', 'Comedy, Music Videos and Concerts', 'Comedy, Romance', 'Comedy, Romance, Special Interest', 'Comedy, Romance, Young Adult Audience', 'Comedy, Science Fiction', 'Comedy, Special Interest', 'Comedy, Special Interest, Unscripted', 'Comedy, Sports', 'Comedy, Sports, Young Adult Audience', 'Comedy, Suspense', 'Comedy, Talk Show and Variety', 'Comedy, Unscripted', 'Comedy, Western', 'Comedy, Young Adult Audience', 'Documentary', 'Documentary, Drama', 'Documentary, Drama, Faith and Spirituality', 'Documentary, Drama, Horror', 'Documentary, Drama, Kids', 'Documentary, Drama, LGBTQ', 'Documentary, Drama, Special Interest', 'Documentary, Drama, Sports', 'Documentary, Drama, Suspense', 'Documentary, Drama, Unscripted', 'Documentary, Faith and Spirituality', 'Documentary, Faith and Spirituality, Music Videos and Concerts', 'Documentary, Faith and Spirituality, Special Interest', 'Documentary, Horror', 'Documentary, Horror, Special Interest', 'Documentary, Horror, Suspense', 'Documentary, International', 'Documentary, International, Special Interest', 'Documentary, Kids', 'Documentary, Kids, Science Fiction', 'Documentary, Kids, Special Interest', 'Documentary, LGBTQ', 'Documentary, LGBTQ, Music Videos and Concerts', 'Documentary, LGBTQ, Special Interest', 'Documentary, Military and War', 'Documentary, Military and War, Special Interest', 'Documentary, Music Videos and Concerts', 'Documentary, Music Videos and Concerts, Special Interest', 'Documentary, Science Fiction', 'Documentary, Science Fiction, Special Interest', 'Documentary, Special Interest', 'Documentary, Special Interest, Sports', 'Documentary, Special Interest, Unscripted', 'Documentary, Sports', 'Documentary, Sports, Unscripted', 'Documentary, Suspense', 'Documentary, Suspense, Unscripted', 'Documentary, Talk Show and Variety', 'Documentary, Unscripted', 'Drama', 'Drama, Faith and Spirituality', 'Drama, Faith and Spirituality, Kids', 'Drama, Faith and Spirituality, LGBTQ', 'Drama, Faith and Spirituality, Romance', 'Drama, Faith and Spirituality, Special Interest', 'Drama, Faith and Spirituality, Suspense', 'Drama, Fantasy', 'Drama, Fantasy, Historical', 'Drama, Fantasy, Kids', 'Drama, Fantasy, Science Fiction', 'Drama, Fantasy, Sports', 'Drama, Fantasy, Suspense', 'Drama, Historical', 'Drama, Historical, International', 'Drama, Historical, Military and War', 'Drama, Historical, Romance', 'Drama, Historical, Suspense', 'Drama, Horror', 'Drama, Horror, International', 'Drama, Horror, Romance', 'Drama, Horror, Science Fiction', 'Drama, Horror, Special Interest', 'Drama, Horror, Suspense', 'Drama, Horror, Western', 'Drama, Horror, Young Adult Audience', 'Drama, International', 'Drama, International, Kids', 'Drama, International, Romance', 'Drama, International, Special Interest', 'Drama, International, Sports', 'Drama, International, Suspense', 'Drama, International, Western', 'Drama, Kids', 'Drama, Kids, LGBTQ', 'Drama, Kids, Romance', 'Drama, Kids, Special Interest', 'Drama, Kids, Suspense', 'Drama, Kids, Western', 'Drama, LGBTQ', 'Drama, LGBTQ, Romance', 'Drama, LGBTQ, Suspense', 'Drama, LGBTQ, Unscripted', 'Drama, LGBTQ, Young Adult Audience', 'Drama, Military and War', 'Drama, Military and War, Suspense', 'Drama, Music Videos and Concerts', 'Drama, Romance', 'Drama, Romance, Science Fiction', 'Drama, Romance, Special Interest', 'Drama, Romance, Suspense', 'Drama, Romance, Western', 'Drama, Science Fiction', 'Drama, Science Fiction, Special Interest', 'Drama, Science Fiction, Suspense', 'Drama, Special Interest', 'Drama, Special Interest, Sports', 'Drama, Special Interest, Suspense', 'Drama, Special Interest, Unscripted', 'Drama, Sports', 'Drama, Suspense', 'Drama, Suspense, Western', 'Drama, Suspense, Young Adult Audience', 'Drama, Unscripted', 'Drama, Unscripted, Young Adult Audience', 'Drama, Western', 'Drama, Young Adult Audience', 'Faith and Spirituality', 'Faith and Spirituality, Kids, Special Interest', 'Faith and Spirituality, Kids, Western', 'Faith and Spirituality, Music Videos and Concerts', 'Faith and Spirituality, Special Interest', 'Faith and Spirituality, Special Interest, Western', 'Fantasy, Horror', 'Fantasy, Horror, International', 'Fantasy, Horror, Science Fiction', 'Fantasy, Kids', 'Fantasy, Science Fiction', 'Fantasy, Science Fiction, Suspense', 'Fantasy, Suspense', 'Fitness', 'Fitness, Kids', 'Fitness, Kids, Special Interest', 'Fitness, Special Interest', 'Historical', 'Historical, Horror, Western', 'Horror', 'Horror, International', 'Horror, International, Science Fiction', 'Horror, International, Suspense', 'Horror, Romance', 'Horror, Romance, Science Fiction', 'Horror, Romance, Suspense', 'Horror, Romance, Western', 'Horror, Science Fiction', 'Horror, Science Fiction, Suspense', 'Horror, Suspense', 'Horror, Suspense, Young Adult Audience', 'Horror, Unscripted', 'Horror, Western', 'Horror, Young Adult Audience', 'International', 'International, LGBTQ, Suspense', 'International, Music Videos and Concerts, Unscripted', 'International, Romance', 'International, Science Fiction, Suspense', 'International, Special Interest', 'International, Sports', 'International, Suspense', 'International, Unscripted', 'Kids', 'Kids, LGBTQ, Romance', 'Kids, Music Videos and Concerts', 'Kids, Science Fiction', 'Kids, Special Interest', 'Kids, Special Interest, Sports', 'Kids, Special Interest, Unscripted', 'Kids, Sports', 'Kids, Western', 'LGBTQ', 'LGBTQ, Romance', 'LGBTQ, Romance, Sports', 'LGBTQ, Special Interest, Unscripted', 'LGBTQ, Suspense', 'Military and War', 'Military and War, Special Interest', 'Military and War, Western', 'Music Videos and Concerts', 'Music Videos and Concerts, Special Interest', 'Romance', 'Romance, Science Fiction', 'Romance, Science Fiction, Suspense', 'Romance, Science Fiction, Western', 'Romance, Suspense', 'Romance, Suspense, Western', 'Romance, Western', 'Science Fiction', 'Science Fiction, Suspense', 'Science Fiction, Suspense, Unscripted', 'Special Interest', 'Special Interest, Sports', 'Special Interest, Suspense', 'Special Interest, Talk Show and Variety, Unscripted', 'Special Interest, Unscripted', 'Special Interest, Western', 'Sports', 'Sports, Unscripted', 'Suspense', 'Suspense, Western', 'TV Shows', 'Talk Show and Variety', 'Unscripted', 'Western', 'Young Adult Audience']

In [134]:
#Exporting The Actual Unique Values Of All Genres From 'listed_in' Column
all_genres = set()

for genres in df['listed_in'].dropna():
    for genre in genres.split(','):
        all_genres.add(genre.strip())

all_genres = sorted(all_genres)

print(all_genres)
print(f"\nTotal unique genres: {len(all_genres)}")

['Action', 'Adventure', 'Animation', 'Anime', 'Arthouse', 'Arts', 'Comedy', 'Documentary', 'Drama', 'Entertainment', 'Faith and Spirituality', 'Fantasy', 'Fitness', 'Historical', 'Horror', 'International', 'Kids', 'LGBTQ', 'Military and War', 'Music Videos and Concerts', 'Romance', 'Science Fiction', 'Special Interest', 'Sports', 'Suspense', 'TV Shows', 'Talk Show and Variety', 'Unscripted', 'Western', 'Young Adult Audience', 'and Culture']

Total unique genres: 31

In [135]:
#Renaming listed_in Column To Genre
df.rename(columns={'listed_in': 'Genre'}, inplace=True)

In [136]:
print(df.columns)

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'Genre', 'description'],
      dtype='object')

In [137]:
genre_dummies = (
    df['Genre']
    .str.get_dummies(sep=',')
)

genre_dummies.columns = (
    genre_dummies.columns
    .str.strip()
    .str.replace(' ', '_')
)

genre_dummies = genre_dummies.add_prefix('Genre_')

In [91]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9331 entries, 1 to 9667
Data columns (total 69 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   show_id                          9331 non-null   object
 1   type                             9331 non-null   object
 2   title                            9331 non-null   object
 3   director                         7255 non-null   object
 4   cast                             8123 non-null   object
 5   country                          657 non-null    object
 6   date_added                       140 non-null    object
 7   release_year                     9331 non-null   int64
 8   rating                           9331 non-null   object
 9   duration                         9331 non-null   object
 10  Genre                            9331 non-null   object
 11  description                      9331 non-null   object
 12  Genre_Adventure                  9331 non-null   int64
 13  Genre_Animation                  9331 non-null   int64
 14  Genre_Anime                      9331 non-null   int64
 15  Genre_Arthouse                   9331 non-null   int64
 16  Genre_Arts                       9331 non-null   int64
 17  Genre_Comedy                     9331 non-null   int64
 18  Genre_Documentary                9331 non-null   int64
 19  Genre_Drama                      9331 non-null   int64
 20  Genre_Entertainment              9331 non-null   int64
 21  Genre_Faith and Spirituality     9331 non-null   int64
 22  Genre_Fantasy                    9331 non-null   int64
 23  Genre_Historical                 9331 non-null   int64
 24  Genre_Horror                     9331 non-null   int64
 25  Genre_International              9331 non-null   int64
 26  Genre_Kids                       9331 non-null   int64
 27  Genre_LGBTQ                      9331 non-null   int64
 28  Genre_Military and War           9331 non-null   int64
 29  Genre_Music Videos and Concerts  9331 non-null   int64
 30  Genre_Romance                    9331 non-null   int64
 31  Genre_Science Fiction            9331 non-null   int64
 32  Genre_Special Interest           9331 non-null   int64
 33  Genre_Sports                     9331 non-null   int64
 34  Genre_Suspense                   9331 non-null   int64
 35  Genre_Talk Show and Variety      9331 non-null   int64
 36  Genre_Unscripted                 9331 non-null   int64
 37  Genre_Western                    9331 non-null   int64
 38  Genre_Young Adult Audience       9331 non-null   int64
 39  Genre_and Culture                9331 non-null   int64
 40  Genre_Action                     9331 non-null   int64
 41  Genre_Adventure                  9331 non-null   int64
 42  Genre_Animation                  9331 non-null   int64
 43  Genre_Anime                      9331 non-null   int64
 44  Genre_Arthouse                   9331 non-null   int64
 45  Genre_Arts                       9331 non-null   int64
 46  Genre_Comedy                     9331 non-null   int64
 47  Genre_Documentary                9331 non-null   int64
 48  Genre_Drama                      9331 non-null   int64
 49  Genre_Faith and Spirituality     9331 non-null   int64
 50  Genre_Fantasy                    9331 non-null   int64
 51  Genre_Fitness                    9331 non-null   int64
 52  Genre_Historical                 9331 non-null   int64
 53  Genre_Horror                     9331 non-null   int64
 54  Genre_International              9331 non-null   int64
 55  Genre_Kids                       9331 non-null   int64
 56  Genre_LGBTQ                      9331 non-null   int64
 57  Genre_Military and War           9331 non-null   int64
 58  Genre_Music Videos and Concerts  9331 non-null   int64
 59  Genre_Romance                    9331 non-null   int64
 60  Genre_Science Fiction            9331 non-null   int64
 61  Genre_Special Interest           9331 non-null   int64
 62  Genre_Sports                     9331 non-null   int64
 63  Genre_Suspense                   9331 non-null   int64
 64  Genre_TV Shows                   9331 non-null   int64
 65  Genre_Talk Show and Variety      9331 non-null   int64
 66  Genre_Unscripted                 9331 non-null   int64
 67  Genre_Western                    9331 non-null   int64
 68  Genre_Young Adult Audience       9331 non-null   int64
dtypes: int64(58), object(11)
memory usage: 5.0+ MB

In [92]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,...,Genre_Romance,Genre_Science Fiction,Genre_Special Interest,Genre_Sports,Genre_Suspense,Genre_TV Shows,Genre_Talk Show and Variety,Genre_Unscripted,Genre_Western,Genre_Young Adult Audience
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,110 min,...,0,0,0,0,0,0,0,0,0,0
16,s17,Movie,Zoombies,Glenn Miller,"Marcus Anderson, Kaiwi Lyman, Andrew Asper",NaN,NaN,2016,13+,87 min,...,0,0,0,0,0,0,0,0,0,0
17,s18,TV Show,Zoo Babies,NaN,Narrator - Gillian Barlett,NaN,NaN,2008,ALL,1 Season,...,0,0,0,0,0,0,0,0,0,0
18,s19,TV Show,Zoë Coombs Marr: Bossy Bottom,NaN,Zoë Coombs Marr,NaN,NaN,2020,18+,1 Season,...,0,0,0,0,0,0,0,0,0,0
19,s20,Movie,Zoe,Drake Doremus,"Ewan McGregor, Léa Seydoux, Theo James, Mirand...",NaN,NaN,2018,R,104 min,...,0,1,0,0,0,0,0,0,0,0

In [95]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9331 entries, 1 to 9667
Data columns (total 69 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   show_id                          9331 non-null   object
 1   type                             9331 non-null   object
 2   title                            9331 non-null   object
 3   director                         7255 non-null   object
 4   cast                             8123 non-null   object
 5   country                          657 non-null    object
 6   date_added                       140 non-null    object
 7   release_year                     9331 non-null   int64
 8   rating                           9331 non-null   object
 9   duration                         9331 non-null   object
 10  Genre                            9331 non-null   object
 11  description                      9331 non-null   object
 12  Genre_Adventure                  9331 non-null   int64
 13  Genre_Animation                  9331 non-null   int64
 14  Genre_Anime                      9331 non-null   int64
 15  Genre_Arthouse                   9331 non-null   int64
 16  Genre_Arts                       9331 non-null   int64
 17  Genre_Comedy                     9331 non-null   int64
 18  Genre_Documentary                9331 non-null   int64
 19  Genre_Drama                      9331 non-null   int64
 20  Genre_Entertainment              9331 non-null   int64
 21  Genre_Faith and Spirituality     9331 non-null   int64
 22  Genre_Fantasy                    9331 non-null   int64
 23  Genre_Historical                 9331 non-null   int64
 24  Genre_Horror                     9331 non-null   int64
 25  Genre_International              9331 non-null   int64
 26  Genre_Kids                       9331 non-null   int64
 27  Genre_LGBTQ                      9331 non-null   int64
 28  Genre_Military and War           9331 non-null   int64
 29  Genre_Music Videos and Concerts  9331 non-null   int64
 30  Genre_Romance                    9331 non-null   int64
 31  Genre_Science Fiction            9331 non-null   int64
 32  Genre_Special Interest           9331 non-null   int64
 33  Genre_Sports                     9331 non-null   int64
 34  Genre_Suspense                   9331 non-null   int64
 35  Genre_Talk Show and Variety      9331 non-null   int64
 36  Genre_Unscripted                 9331 non-null   int64
 37  Genre_Western                    9331 non-null   int64
 38  Genre_Young Adult Audience       9331 non-null   int64
 39  Genre_and Culture                9331 non-null   int64
 40  Genre_Action                     9331 non-null   int64
 41  Genre_Adventure                  9331 non-null   int64
 42  Genre_Animation                  9331 non-null   int64
 43  Genre_Anime                      9331 non-null   int64
 44  Genre_Arthouse                   9331 non-null   int64
 45  Genre_Arts                       9331 non-null   int64
 46  Genre_Comedy                     9331 non-null   int64
 47  Genre_Documentary                9331 non-null   int64
 48  Genre_Drama                      9331 non-null   int64
 49  Genre_Faith and Spirituality     9331 non-null   int64
 50  Genre_Fantasy                    9331 non-null   int64
 51  Genre_Fitness                    9331 non-null   int64
 52  Genre_Historical                 9331 non-null   int64
 53  Genre_Horror                     9331 non-null   int64
 54  Genre_International              9331 non-null   int64
 55  Genre_Kids                       9331 non-null   int64
 56  Genre_LGBTQ                      9331 non-null   int64
 57  Genre_Military and War           9331 non-null   int64
 58  Genre_Music Videos and Concerts  9331 non-null   int64
 59  Genre_Romance                    9331 non-null   int64
 60  Genre_Science Fiction            9331 non-null   int64
 61  Genre_Special Interest           9331 non-null   int64
 62  Genre_Sports                     9331 non-null   int64
 63  Genre_Suspense                   9331 non-null   int64
 64  Genre_TV Shows                   9331 non-null   int64
 65  Genre_Talk Show and Variety      9331 non-null   int64
 66  Genre_Unscripted                 9331 non-null   int64
 67  Genre_Western                    9331 non-null   int64
 68  Genre_Young Adult Audience       9331 non-null   int64
dtypes: int64(58), object(11)
memory usage: 5.0+ MB

In [138]:
df = df.loc[:, ~df.columns.duplicated()]

In [140]:
genre_dummies = df['Genre'].str.get_dummies(sep=',')

# clean column names
genre_dummies.columns = genre_dummies.columns.str.strip()

# add prefix
genre_dummies = genre_dummies.add_prefix('Genre_')

# merge
df = pd.concat([df, genre_dummies], axis=1)

In [142]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9331 entries, 1 to 9667
Data columns (total 69 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   show_id                          9331 non-null   object
 1   type                             9331 non-null   object
 2   title                            9331 non-null   object
 3   director                         7255 non-null   object
 4   cast                             8123 non-null   object
 5   country                          657 non-null    object
 6   date_added                       140 non-null    object
 7   release_year                     9331 non-null   int64
 8   rating                           9331 non-null   object
 9   duration                         9331 non-null   object
 10  Genre                            9331 non-null   object
 11  description                      9331 non-null   object
 12  Genre_Adventure                  9331 non-null   int64
 13  Genre_Animation                  9331 non-null   int64
 14  Genre_Anime                      9331 non-null   int64
 15  Genre_Arthouse                   9331 non-null   int64
 16  Genre_Arts                       9331 non-null   int64
 17  Genre_Comedy                     9331 non-null   int64
 18  Genre_Documentary                9331 non-null   int64
 19  Genre_Drama                      9331 non-null   int64
 20  Genre_Entertainment              9331 non-null   int64
 21  Genre_Faith and Spirituality     9331 non-null   int64
 22  Genre_Fantasy                    9331 non-null   int64
 23  Genre_Historical                 9331 non-null   int64
 24  Genre_Horror                     9331 non-null   int64
 25  Genre_International              9331 non-null   int64
 26  Genre_Kids                       9331 non-null   int64
 27  Genre_LGBTQ                      9331 non-null   int64
 28  Genre_Military and War           9331 non-null   int64
 29  Genre_Music Videos and Concerts  9331 non-null   int64
 30  Genre_Romance                    9331 non-null   int64
 31  Genre_Science Fiction            9331 non-null   int64
 32  Genre_Special Interest           9331 non-null   int64
 33  Genre_Sports                     9331 non-null   int64
 34  Genre_Suspense                   9331 non-null   int64
 35  Genre_Talk Show and Variety      9331 non-null   int64
 36  Genre_Unscripted                 9331 non-null   int64
 37  Genre_Western                    9331 non-null   int64
 38  Genre_Young Adult Audience       9331 non-null   int64
 39  Genre_and Culture                9331 non-null   int64
 40  Genre_Action                     9331 non-null   int64
 41  Genre_Adventure                  9331 non-null   int64
 42  Genre_Animation                  9331 non-null   int64
 43  Genre_Anime                      9331 non-null   int64
 44  Genre_Arthouse                   9331 non-null   int64
 45  Genre_Arts                       9331 non-null   int64
 46  Genre_Comedy                     9331 non-null   int64
 47  Genre_Documentary                9331 non-null   int64
 48  Genre_Drama                      9331 non-null   int64
 49  Genre_Faith and Spirituality     9331 non-null   int64
 50  Genre_Fantasy                    9331 non-null   int64
 51  Genre_Fitness                    9331 non-null   int64
 52  Genre_Historical                 9331 non-null   int64
 53  Genre_Horror                     9331 non-null   int64
 54  Genre_International              9331 non-null   int64
 55  Genre_Kids                       9331 non-null   int64
 56  Genre_LGBTQ                      9331 non-null   int64
 57  Genre_Military and War           9331 non-null   int64
 58  Genre_Music Videos and Concerts  9331 non-null   int64
 59  Genre_Romance                    9331 non-null   int64
 60  Genre_Science Fiction            9331 non-null   int64
 61  Genre_Special Interest           9331 non-null   int64
 62  Genre_Sports                     9331 non-null   int64
 63  Genre_Suspense                   9331 non-null   int64
 64  Genre_TV Shows                   9331 non-null   int64
 65  Genre_Talk Show and Variety      9331 non-null   int64
 66  Genre_Unscripted                 9331 non-null   int64
 67  Genre_Western                    9331 non-null   int64
 68  Genre_Young Adult Audience       9331 non-null   int64
dtypes: int64(58), object(11)
memory usage: 5.0+ MB

In [143]:
df['Genre'] = df['Genre'].fillna('')

df['Genre'] = df['Genre'].apply(
    lambda x: ','.join([i.strip() for i in x.split(',')])
)

In [144]:
df = df.drop(columns=[col for col in df.columns if col.startswith("Genre_")], errors='ignore')

In [145]:
genre_dummies = df['Genre'].str.get_dummies(sep=',')

# clean column names
genre_dummies.columns = genre_dummies.columns.str.strip()

# add prefix
genre_dummies = genre_dummies.add_prefix('Genre_')

# merge
df = pd.concat([df, genre_dummies], axis=1)

In [146]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9331 entries, 1 to 9667
Data columns (total 43 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   show_id                          9331 non-null   object
 1   type                             9331 non-null   object
 2   title                            9331 non-null   object
 3   director                         7255 non-null   object
 4   cast                             8123 non-null   object
 5   country                          657 non-null    object
 6   date_added                       140 non-null    object
 7   release_year                     9331 non-null   int64
 8   rating                           9331 non-null   object
 9   duration                         9331 non-null   object
 10  Genre                            9331 non-null   object
 11  description                      9331 non-null   object
 12  Genre_Action                     9331 non-null   int64
 13  Genre_Adventure                  9331 non-null   int64
 14  Genre_Animation                  9331 non-null   int64
 15  Genre_Anime                      9331 non-null   int64
 16  Genre_Arthouse                   9331 non-null   int64
 17  Genre_Arts                       9331 non-null   int64
 18  Genre_Comedy                     9331 non-null   int64
 19  Genre_Documentary                9331 non-null   int64
 20  Genre_Drama                      9331 non-null   int64
 21  Genre_Entertainment              9331 non-null   int64
 22  Genre_Faith and Spirituality     9331 non-null   int64
 23  Genre_Fantasy                    9331 non-null   int64
 24  Genre_Fitness                    9331 non-null   int64
 25  Genre_Historical                 9331 non-null   int64
 26  Genre_Horror                     9331 non-null   int64
 27  Genre_International              9331 non-null   int64
 28  Genre_Kids                       9331 non-null   int64
 29  Genre_LGBTQ                      9331 non-null   int64
 30  Genre_Military and War           9331 non-null   int64
 31  Genre_Music Videos and Concerts  9331 non-null   int64
 32  Genre_Romance                    9331 non-null   int64
 33  Genre_Science Fiction            9331 non-null   int64
 34  Genre_Special Interest           9331 non-null   int64
 35  Genre_Sports                     9331 non-null   int64
 36  Genre_Suspense                   9331 non-null   int64
 37  Genre_TV Shows                   9331 non-null   int64
 38  Genre_Talk Show and Variety      9331 non-null   int64
 39  Genre_Unscripted                 9331 non-null   int64
 40  Genre_Western                    9331 non-null   int64
 41  Genre_Young Adult Audience       9331 non-null   int64
 42  Genre_and Culture                9331 non-null   int64
dtypes: int64(32), object(11)
memory usage: 3.1+ MB

In [147]:
print([col for col in df.columns if col.startswith("Genre_")])
print("Total genre columns:", len([col for col in df.columns if col.startswith("Genre_")]))

['Genre_Action', 'Genre_Adventure', 'Genre_Animation', 'Genre_Anime', 'Genre_Arthouse', 'Genre_Arts', 'Genre_Comedy', 'Genre_Documentary', 'Genre_Drama', 'Genre_Entertainment', 'Genre_Faith and Spirituality', 'Genre_Fantasy', 'Genre_Fitness', 'Genre_Historical', 'Genre_Horror', 'Genre_International', 'Genre_Kids', 'Genre_LGBTQ', 'Genre_Military and War', 'Genre_Music Videos and Concerts', 'Genre_Romance', 'Genre_Science Fiction', 'Genre_Special Interest', 'Genre_Sports', 'Genre_Suspense', 'Genre_TV Shows', 'Genre_Talk Show and Variety', 'Genre_Unscripted', 'Genre_Western', 'Genre_Young Adult Audience', 'Genre_and Culture']
Total genre columns: 31

In [149]:
#Now Clearing Leading And Trailing Space From The Values Of All The Columns 
df = df.apply(lambda col: col.str.strip() if col.dtype == "object" else col)

In [150]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,...,Genre_Science Fiction,Genre_Special Interest,Genre_Sports,Genre_Suspense,Genre_TV Shows,Genre_Talk Show and Variety,Genre_Unscripted,Genre_Western,Genre_Young Adult Audience,Genre_and Culture
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,110 min,...,0,0,0,0,0,0,0,0,0,0
16,s17,Movie,Zoombies,Glenn Miller,"Marcus Anderson, Kaiwi Lyman, Andrew Asper",NaN,NaN,2016,13+,87 min,...,1,0,0,0,0,0,0,0,0,0
17,s18,TV Show,Zoo Babies,NaN,Narrator - Gillian Barlett,NaN,NaN,2008,ALL,1 Season,...,0,1,0,0,0,0,0,0,0,0
18,s19,TV Show,Zoë Coombs Marr: Bossy Bottom,NaN,Zoë Coombs Marr,NaN,NaN,2020,18+,1 Season,...,0,0,0,0,0,1,0,0,0,0
19,s20,Movie,Zoe,Drake Doremus,"Ewan McGregor, Léa Seydoux, Theo James, Mirand...",NaN,NaN,2018,R,104 min,...,1,0,0,0,0,0,0,0,0,0

In [151]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9331 entries, 1 to 9667
Data columns (total 43 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   show_id                          9331 non-null   object
 1   type                             9331 non-null   object
 2   title                            9331 non-null   object
 3   director                         7255 non-null   object
 4   cast                             8123 non-null   object
 5   country                          657 non-null    object
 6   date_added                       140 non-null    object
 7   release_year                     9331 non-null   int64
 8   rating                           9331 non-null   object
 9   duration                         9331 non-null   object
 10  Genre                            9331 non-null   object
 11  description                      9331 non-null   object
 12  Genre_Action                     9331 non-null   int64
 13  Genre_Adventure                  9331 non-null   int64
 14  Genre_Animation                  9331 non-null   int64
 15  Genre_Anime                      9331 non-null   int64
 16  Genre_Arthouse                   9331 non-null   int64
 17  Genre_Arts                       9331 non-null   int64
 18  Genre_Comedy                     9331 non-null   int64
 19  Genre_Documentary                9331 non-null   int64
 20  Genre_Drama                      9331 non-null   int64
 21  Genre_Entertainment              9331 non-null   int64
 22  Genre_Faith and Spirituality     9331 non-null   int64
 23  Genre_Fantasy                    9331 non-null   int64
 24  Genre_Fitness                    9331 non-null   int64
 25  Genre_Historical                 9331 non-null   int64
 26  Genre_Horror                     9331 non-null   int64
 27  Genre_International              9331 non-null   int64
 28  Genre_Kids                       9331 non-null   int64
 29  Genre_LGBTQ                      9331 non-null   int64
 30  Genre_Military and War           9331 non-null   int64
 31  Genre_Music Videos and Concerts  9331 non-null   int64
 32  Genre_Romance                    9331 non-null   int64
 33  Genre_Science Fiction            9331 non-null   int64
 34  Genre_Special Interest           9331 non-null   int64
 35  Genre_Sports                     9331 non-null   int64
 36  Genre_Suspense                   9331 non-null   int64
 37  Genre_TV Shows                   9331 non-null   int64
 38  Genre_Talk Show and Variety      9331 non-null   int64
 39  Genre_Unscripted                 9331 non-null   int64
 40  Genre_Western                    9331 non-null   int64
 41  Genre_Young Adult Audience       9331 non-null   int64
 42  Genre_and Culture                9331 non-null   int64
dtypes: int64(32), object(11)
memory usage: 3.1+ MB

In [152]:
#Considered removing the date_Added,country as both has a lot many null values
#but keeping it and will not use it for any analysis.so they are useless column for now
df['country'] = df['country'].str.strip()

In [153]:
df['country'].unique()

array(['India', nan, 'Italy', 'United States', 'United Kingdom, France',
       'United States, Italy', 'United States, India',
       'United Kingdom, United States',
       'United States, United Kingdom, Germany', 'Japan',
       'China, United States, United Kingdom',
       'Denmark, United Kingdom, Czech Republic, Netherlands',
       'United Kingdom', 'Canada', 'United States, Ireland',
       'United States, United Kingdom, Canada',
       'United Kingdom, United States, India', 'United Kingdom, India',
       'United States, China', 'Canada, United States',
       'United States, Thailand', 'Spain', 'Brazil, United States, India',
       'Switzerland, India', 'United Kingdom, Canada, United States',
       'Germany', 'Australia', 'Belgium',
       'Chile, Argentina, United States', 'Mexico',
       'Denmark, Sweden, United States', 'Netherlands',
       'United States, United Kingdom', 'New Zealand',
       'United States, Portugal', 'United States, France',
       'Canada, United States, Brazil', 'France, United States',
       'India, United States', 'India, Sweden',
       'United Kingdom, Hungary, United States',
       'Czech Republic, Germany', 'United Kingdom, France, United States',
       'Iran, France', 'United States, France, Denmark', 'Brazil',
       'Ireland, Belgium, France, Luxembourg, United Kingdom',
       'United States, Germany, Brazil, Italy', 'South Africa',
       'Australia, United States, Germany',
       'Germany, Austria, United States',
       'France, China, Belgium, Monaco', 'Egypt',
       'United States, Austria', 'United States, United Arab Emirates',
       'United States, Belgium, Denmark, France', 'Switzerland',
       'United States, Canada',
       'India, United States, United Kingdom, Canada, China',
       'India, South Africa, Brazil', 'United States, Germany',
       'United States, Japan, Singapore, South Korea',
       'Afghanistan, France', 'Australia, Colombia, United Kingdom',
       'United States, Sweden, Norway', 'Kosovo, Netherlands',
       'Spain, United Kingdom, Italy', 'Austria', 'United Kingdom, Spain',
       'United States, United Kingdom, Kazakhstan', 'Malaysia',
       'Poland, United States', 'Canada, Germany', 'India, Denmark',
       'United States, Switzerland', 'United States, Germany, Italy',
       'France', 'Denmark, France', 'Japan, France',
       'Kosovo, Albania, United States, Georgia', 'United States, Japan',
       'Germany, Canada, United States, France, United Kingdom',
       'United States, Mexico',
       'United States, Germany, Japan, United Kingdom, Hong Kong',
       'Italy, Canada', 'France, Belgium', 'Italy, Spain'], dtype=object)

In [154]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9331 entries, 1 to 9667
Data columns (total 43 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   show_id                          9331 non-null   object
 1   type                             9331 non-null   object
 2   title                            9331 non-null   object
 3   director                         7255 non-null   object
 4   cast                             8123 non-null   object
 5   country                          657 non-null    object
 6   date_added                       140 non-null    object
 7   release_year                     9331 non-null   int64
 8   rating                           9331 non-null   object
 9   duration                         9331 non-null   object
 10  Genre                            9331 non-null   object
 11  description                      9331 non-null   object
 12  Genre_Action                     9331 non-null   int64
 13  Genre_Adventure                  9331 non-null   int64
 14  Genre_Animation                  9331 non-null   int64
 15  Genre_Anime                      9331 non-null   int64
 16  Genre_Arthouse                   9331 non-null   int64
 17  Genre_Arts                       9331 non-null   int64
 18  Genre_Comedy                     9331 non-null   int64
 19  Genre_Documentary                9331 non-null   int64
 20  Genre_Drama                      9331 non-null   int64
 21  Genre_Entertainment              9331 non-null   int64
 22  Genre_Faith and Spirituality     9331 non-null   int64
 23  Genre_Fantasy                    9331 non-null   int64
 24  Genre_Fitness                    9331 non-null   int64
 25  Genre_Historical                 9331 non-null   int64
 26  Genre_Horror                     9331 non-null   int64
 27  Genre_International              9331 non-null   int64
 28  Genre_Kids                       9331 non-null   int64
 29  Genre_LGBTQ                      9331 non-null   int64
 30  Genre_Military and War           9331 non-null   int64
 31  Genre_Music Videos and Concerts  9331 non-null   int64
 32  Genre_Romance                    9331 non-null   int64
 33  Genre_Science Fiction            9331 non-null   int64
 34  Genre_Special Interest           9331 non-null   int64
 35  Genre_Sports                     9331 non-null   int64
 36  Genre_Suspense                   9331 non-null   int64
 37  Genre_TV Shows                   9331 non-null   int64
 38  Genre_Talk Show and Variety      9331 non-null   int64
 39  Genre_Unscripted                 9331 non-null   int64
 40  Genre_Western                    9331 non-null   int64
 41  Genre_Young Adult Audience       9331 non-null   int64
 42  Genre_and Culture                9331 non-null   int64
dtypes: int64(32), object(11)
memory usage: 3.1+ MB

In [155]:
#Removing Rows Containing Null Values Of Cast Column 
df = df.dropna(subset=['cast'])

In [156]:
print(df['cast'].isna().sum())
print(df.shape)

0
(8123, 43)

In [157]:
df.info()
#now one more problem director column has null values aprrox 1500+ which is a bad news but let's keep those

<class 'pandas.core.frame.DataFrame'>
Index: 8123 entries, 1 to 9667
Data columns (total 43 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   show_id                          8123 non-null   object
 1   type                             8123 non-null   object
 2   title                            8123 non-null   object
 3   director                         6645 non-null   object
 4   cast                             8123 non-null   object
 5   country                          640 non-null    object
 6   date_added                       93 non-null     object
 7   release_year                     8123 non-null   int64
 8   rating                           8123 non-null   object
 9   duration                         8123 non-null   object
 10  Genre                            8123 non-null   object
 11  description                      8123 non-null   object
 12  Genre_Action                     8123 non-null   int64
 13  Genre_Adventure                  8123 non-null   int64
 14  Genre_Animation                  8123 non-null   int64
 15  Genre_Anime                      8123 non-null   int64
 16  Genre_Arthouse                   8123 non-null   int64
 17  Genre_Arts                       8123 non-null   int64
 18  Genre_Comedy                     8123 non-null   int64
 19  Genre_Documentary                8123 non-null   int64
 20  Genre_Drama                      8123 non-null   int64
 21  Genre_Entertainment              8123 non-null   int64
 22  Genre_Faith and Spirituality     8123 non-null   int64
 23  Genre_Fantasy                    8123 non-null   int64
 24  Genre_Fitness                    8123 non-null   int64
 25  Genre_Historical                 8123 non-null   int64
 26  Genre_Horror                     8123 non-null   int64
 27  Genre_International              8123 non-null   int64
 28  Genre_Kids                       8123 non-null   int64
 29  Genre_LGBTQ                      8123 non-null   int64
 30  Genre_Military and War           8123 non-null   int64
 31  Genre_Music Videos and Concerts  8123 non-null   int64
 32  Genre_Romance                    8123 non-null   int64
 33  Genre_Science Fiction            8123 non-null   int64
 34  Genre_Special Interest           8123 non-null   int64
 35  Genre_Sports                     8123 non-null   int64
 36  Genre_Suspense                   8123 non-null   int64
 37  Genre_TV Shows                   8123 non-null   int64
 38  Genre_Talk Show and Variety      8123 non-null   int64
 39  Genre_Unscripted                 8123 non-null   int64
 40  Genre_Western                    8123 non-null   int64
 41  Genre_Young Adult Audience       8123 non-null   int64
 42  Genre_and Culture                8123 non-null   int64
dtypes: int64(32), object(11)
memory usage: 2.7+ MB

In [159]:
df.dropna(subset=['director']).info()
#on droping rows containing null values of director all the columns has almost all values but date_Added has reduced to just 
#1 non null value.but we will still drop the null values of director rows.

<class 'pandas.core.frame.DataFrame'>
Index: 6645 entries, 1 to 9667
Data columns (total 43 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   show_id                          6645 non-null   object
 1   type                             6645 non-null   object
 2   title                            6645 non-null   object
 3   director                         6645 non-null   object
 4   cast                             6645 non-null   object
 5   country                          538 non-null    object
 6   date_added                       1 non-null      object
 7   release_year                     6645 non-null   int64
 8   rating                           6645 non-null   object
 9   duration                         6645 non-null   object
 10  Genre                            6645 non-null   object
 11  description                      6645 non-null   object
 12  Genre_Action                     6645 non-null   int64
 13  Genre_Adventure                  6645 non-null   int64
 14  Genre_Animation                  6645 non-null   int64
 15  Genre_Anime                      6645 non-null   int64
 16  Genre_Arthouse                   6645 non-null   int64
 17  Genre_Arts                       6645 non-null   int64
 18  Genre_Comedy                     6645 non-null   int64
 19  Genre_Documentary                6645 non-null   int64
 20  Genre_Drama                      6645 non-null   int64
 21  Genre_Entertainment              6645 non-null   int64
 22  Genre_Faith and Spirituality     6645 non-null   int64
 23  Genre_Fantasy                    6645 non-null   int64
 24  Genre_Fitness                    6645 non-null   int64
 25  Genre_Historical                 6645 non-null   int64
 26  Genre_Horror                     6645 non-null   int64
 27  Genre_International              6645 non-null   int64
 28  Genre_Kids                       6645 non-null   int64
 29  Genre_LGBTQ                      6645 non-null   int64
 30  Genre_Military and War           6645 non-null   int64
 31  Genre_Music Videos and Concerts  6645 non-null   int64
 32  Genre_Romance                    6645 non-null   int64
 33  Genre_Science Fiction            6645 non-null   int64
 34  Genre_Special Interest           6645 non-null   int64
 35  Genre_Sports                     6645 non-null   int64
 36  Genre_Suspense                   6645 non-null   int64
 37  Genre_TV Shows                   6645 non-null   int64
 38  Genre_Talk Show and Variety      6645 non-null   int64
 39  Genre_Unscripted                 6645 non-null   int64
 40  Genre_Western                    6645 non-null   int64
 41  Genre_Young Adult Audience       6645 non-null   int64
 42  Genre_and Culture                6645 non-null   int64
dtypes: int64(32), object(11)
memory usage: 2.2+ MB

In [160]:
df = df.dropna(subset=['director'])

In [161]:
print(df['director'].isna().sum())
print(df.shape)

0
(6645, 43)

In [162]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6645 entries, 1 to 9667
Data columns (total 43 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   show_id                          6645 non-null   object
 1   type                             6645 non-null   object
 2   title                            6645 non-null   object
 3   director                         6645 non-null   object
 4   cast                             6645 non-null   object
 5   country                          538 non-null    object
 6   date_added                       1 non-null      object
 7   release_year                     6645 non-null   int64
 8   rating                           6645 non-null   object
 9   duration                         6645 non-null   object
 10  Genre                            6645 non-null   object
 11  description                      6645 non-null   object
 12  Genre_Action                     6645 non-null   int64
 13  Genre_Adventure                  6645 non-null   int64
 14  Genre_Animation                  6645 non-null   int64
 15  Genre_Anime                      6645 non-null   int64
 16  Genre_Arthouse                   6645 non-null   int64
 17  Genre_Arts                       6645 non-null   int64
 18  Genre_Comedy                     6645 non-null   int64
 19  Genre_Documentary                6645 non-null   int64
 20  Genre_Drama                      6645 non-null   int64
 21  Genre_Entertainment              6645 non-null   int64
 22  Genre_Faith and Spirituality     6645 non-null   int64
 23  Genre_Fantasy                    6645 non-null   int64
 24  Genre_Fitness                    6645 non-null   int64
 25  Genre_Historical                 6645 non-null   int64
 26  Genre_Horror                     6645 non-null   int64
 27  Genre_International              6645 non-null   int64
 28  Genre_Kids                       6645 non-null   int64
 29  Genre_LGBTQ                      6645 non-null   int64
 30  Genre_Military and War           6645 non-null   int64
 31  Genre_Music Videos and Concerts  6645 non-null   int64
 32  Genre_Romance                    6645 non-null   int64
 33  Genre_Science Fiction            6645 non-null   int64
 34  Genre_Special Interest           6645 non-null   int64
 35  Genre_Sports                     6645 non-null   int64
 36  Genre_Suspense                   6645 non-null   int64
 37  Genre_TV Shows                   6645 non-null   int64
 38  Genre_Talk Show and Variety      6645 non-null   int64
 39  Genre_Unscripted                 6645 non-null   int64
 40  Genre_Western                    6645 non-null   int64
 41  Genre_Young Adult Audience       6645 non-null   int64
 42  Genre_and Culture                6645 non-null   int64
dtypes: int64(32), object(11)
memory usage: 2.2+ MB

In [165]:
#Renaming Genre_and Culture to Genre_Culture
df.rename(columns={'Genre_and Culture': 'Genre_Culture'}, inplace=True)

In [166]:
df.to_csv("cleaned_dataset.csv", index=False)

🌞What We Did Today :-

---

# ➡️ Dataset Cleaning & Transformation Summary

## 1. Initial Data Understanding

* Explored dataset using `df.info()`
* Identified key columns:

  * `rating`, `listed_in`, `cast`, `director`, `country`, `date_added`
* Noticed missing values and multi-value columns (like genres)

---

## 2. Handling Missing Values

* **Dropped rows with missing `rating`**

  ```python
  df = df.dropna(subset=['rating'])
  ```
* **Decision on `director` and `cast`:**

  * Preferred keeping data instead of losing rows
  * Optionally replaced missing values with `"Unknown"`

---

## 3. Cleaning Text Data

* Removed leading/trailing spaces in:

  * Column names
  * All string/object values

```python
df.columns = df.columns.str.strip()

df = df.apply(lambda col: col.str.strip() if col.dtype == "object" else col)
```

---

## 4. Genre Column Transformation (Major Step)

### Problem:

* `listed_in` had combined values like:

  ```
  Action, Adventure, Comedy
  ```
* This created incorrect “unique values” (512 combinations)

### Solution:

* Split genres into individual values
* Cleaned spaces and inconsistencies

```python
df['Genre'] = df['Genre'].apply(lambda x: ','.join([i.strip() for i in x.split(',')]))
```

---

## 5. One-Hot Encoding for Genre

* Converted multi-label genres into binary columns

```python
genre_dummies = df['Genre'].str.get_dummies(sep=',')
genre_dummies.columns = genre_dummies.columns.str.strip()
genre_dummies = genre_dummies.add_prefix('Genre_')
df = pd.concat([df, genre_dummies], axis=1)
```

### Fixes applied:

* Removed duplicate genre columns
* Fixed spacing issues causing duplicate columns

---

## 6. Column Standardization

* Renamed:

  * `listed_in` → `Genre`
* Fixed inconsistent column name:

  * `Genre_and Culture` → `Genre_Culture`

```python
df.rename(columns={'Genre_and Culture': 'Genre_Culture'}, inplace=True)
```

---

## 7. Handling Sparse Columns

### `date_added`

* Only ~140 values
* Kept but marked as optional

### `country`

* ~657 values
* Decided to keep for potential analysis

---

## 8. Exporting Final Dataset

* Saved cleaned dataset for Power BI / analysis

```python
df.to_csv("cleaned_dataset.csv", index=False)
```

---

# 🎯 Final Outcome

I now have:

* Cleaned dataset (6645 rows)
* Standardized text data
* One-hot encoded genres
* Reduced noise and inconsistencies
* Power BI–ready structure

---

# 🚀 What I Built (Important)

You essentially transformed a raw dataset into:

> A structured analytics-ready dataset with feature engineering (Genre encoding + cleaning + normalization)

---

In [ ]:
"""
Conclusion:
1.After Cleaning The Data We Have Obtained A Dataset Containing 6645 rows which is 68.7% of total rows (Original Dataset : 9668 Rows)
2.Learned About How Complex It Becomes Sometimes Even Just Forgetting To Remove Leading/Trail Spaces.I Encounterred The Problem While Creating Dummies
        Of Genre.
3.Now,Have To Analyse The Data using PowerBI.
"""